Resources:
  RDSCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: ${self:custom.dbLogin} 
      MasterUserPassword: ${self:custom.dbPassword} 
      DatabaseName: MagaDB
      Engine: aurora
      EngineMode: serverless
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 2
        MinCapacity: 1
        SecondsUntilAutoPause: 900
      EnableHttpEndpoint: true
      StorageEncrypted: true
