Resources:
  # Name of the database
  MagaDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userTable} 
      AttributeDefinitions:
        - AttributeName: typeUser
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: fetchTypeUser
          KeySchema:
            - AttributeName: typeUser
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      
        
      # Set the capacity
      BillingMode: PAY_PER_REQUEST