Resources:
  # Name of the database
  MagaDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userTable} 
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: type
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: type
          KeyType: RANGE
        
      # Set the capacity
      BillingMode: PAY_PER_REQUEST