Resources:
  # Name of the database
  MagaDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.userTable} 
      AttributeDefinitions:
        - AttributeName: typeUser
          AttributeType: S
        
      KeySchema:
        - AttributeName: typeUser
          KeyType: HASH
      
        
      # Set the capacity
      BillingMode: PAY_PER_REQUEST